/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Modelika"
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven( "https://jitpack.io" )
        maven("https://papermc.io/repo/repository/maven-public/")
        maven("https://repo.papermc.io/repository/maven-public/")
    }
}